# Generated by Django 4.2.6 on 2023-10-11 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(default='ATOM_number_1', max_length=64, unique=True)),
                ('vim', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_on', models.BooleanField(default=False)),
                ('secure_system', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('station', models.IntegerField(default=950)),
                ('sound', models.IntegerField(default=50)),
                ('is_cruise_on', models.BooleanField(default=False)),
                ('cruise', models.IntegerField(default=40)),
                ('transfer', models.CharField(choices=[('drive', 'drive'), ('sport', 'sport'), ('neutral', 'neutral'), ('back', 'back'), ('park', 'park'), ('brake', 'brake')], default='neutral', max_length=8)),
                ('warnings', models.CharField(choices=[('accept', 'accept'), ('decline', 'decline')], default='off', max_length=8)),
                ('lights', models.CharField(choices=[('near', 'near'), ('antifog', 'antifog'), ('far', 'far'), ('drive', 'drive'), ('off', 'off')], default='drive', max_length=8)),
                ('tires', models.CharField(choices=[('normal', 'normal'), ('flat', 'flat'), ('half', 'half')], default='normal', max_length=8)),
                ('last_transfer_change_time', models.TimeField(blank=True)),
                ('last_wash_lights_time', models.TimeField(blank=True)),
                ('last_wash_glass_time', models.TimeField(blank=True)),
                ('last_call_date', models.DateTimeField(blank=True)),
                ('last_call_command', models.CharField(blank=True, choices=[('call', 'call'), ('accept', 'accept'), ('decline', 'decline')], max_length=8)),
                ('last_invite_time', models.TimeField(blank=True)),
                ('last_parking_time', models.TimeField(blank=True)),
                ('last_lines_change_time', models.TimeField(blank=True)),
                ('last_lines_change_command', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], max_length=8)),
                ('last_gps_date', models.DateTimeField(blank=True)),
                ('last_beep_time', models.TimeField(blank=True)),
                ('last_thanks_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wiper',
            fields=[
                ('position', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('off', 'off'), ('one', 'one'), ('slow', 'slow'), ('medium', 'medium'), ('fast', 'fast')], default='off', max_length=8)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('position', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('open', 'open'), ('close', 'close'), ('half', 'half')], default='close', max_length=8)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('position', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('position', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(default=30)),
                ('is_on', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('position', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('position', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('is_on', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('position', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('position', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(default=25)),
                ('is_on', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
