# Generated by Django 4.2.6 on 2023-10-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_beep_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_call_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_gps_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_invite_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_lines_change_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_parking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_thanks_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_transfer_change_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_wash_glass_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_wash_lights_time',
            field=models.TimeField(null=True),
        ),
    ]
