# Generated by Django 4.2.6 on 2023-10-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_last_beep_time_alter_car_last_call_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trunk',
            name='position',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
