# Generated by Django 4.2.6 on 2023-10-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_trunk_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='position',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
